services:

  # Use a local log directory
  webserver:
    volumes:
      - /share/appdata/qgreenland/release/:/usr/share/nginx/html/:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs:/logs
