version: '3'

services:

  luigi:
    image: nsidc/luigi:dev
    build: .
    container_name: luigi
    volumes:
      - ./luigi/conf:/etc/luigi:ro
      - ./luigi/state:/luigi/state:rw
      - /share/appdata/qgreenland/QGreenland:/luigi/data:rw
      - ./qgreenland:/luigi/tasks/qgreenland:ro
    environment:
      - EARTHDATA_USERNAME
      - EARTHDATA_PASSWORD
    ports:
      - 8082:8082
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    restart: on-failure

  webserver:
    image: nginx
    volumes:
      - /share/appdata/qgreenland/QGreenland/release/:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    restart: on-failure
