version: '3'

services:

  # Luigi runs as a service and must have jobs submitted to it
  # (`scripts/run_task.sh`)
  luigi:
    image: nsidc/luigi:dev
    build: .
    container_name: luigi
    volumes:
      - ./luigi/conf:/etc/luigi:ro
      - ./luigi/state:/luigi/state:rw
      - /share/appdata/qgreenland:/luigi/data:rw
      - ./qgreenland:/luigi/tasks/qgreenland:ro
    environment:
      - ENVIRONMENT
      - EARTHDATA_USERNAME
      - EARTHDATA_PASSWORD
      # Set `export PYTHONBREAKPOINT=ipdb.set_trace` to use `ipdb` by default
      # instead of `pdb`.
      - PYTHONBREAKPOINT
    ports:
      - 8082:8082
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    restart: on-failure

  # QGreenland package hosting
  webserver:
    image: nginx
    volumes:
      - /share/appdata/qgreenland/release/:/usr/share/nginx/html/:ro
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    ports:
      - 80:80
    logging:
      options:
        max-size: "20m"
        max-file: "5"
    restart: on-failure
