name: qgreenland
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.9.7

  #################################################
  # Imported dependencies (and related typestubs) #
  #################################################

  - anytree ~=2.8.0
  - click ~=7.1.2
  - types-click ~=7.1.2
  - fiona ~=1.8.13
  - gdal ~=3.1.4
  - humanize ~=2.6.0
  - luigi ~=3.0.2
  - pydantic ~=1.8
  - qgis ~=3.16.0
  - requests ~=2.25.0
  - types-requests ~=2.25.0


  #############################
  # Non-imported dependencies #
  #############################

  # task-runners
  - invoke ~=1.4.0

  # test-runners
  - pytest ~=6.2
  - pytest-cov ~=2.12

  # static analysis
  - flake8 ~=3.8.3
  - flake8-bugbear ~=20.1.4
  - flake8-comprehensions ~=3.2.2
  - flake8-docstrings ~=1.5.0
  - flake8-import-order ~=0.18.1
  - flake8-quotes ~=2.1.1
  - pep8-naming ~=0.9.1
  - vulture ~=1.0
  - shellcheck ~=0.7.1

  # typechecking
  - mypy ~=0.910

  # other utilities
  - ipython
  - ipdb
  - pip


  # Pip dependencies could be imported or non-imported :(
  - pip:
    - flake8-commas ~=2.0.0
    - flake8-debugger ~=3.2
    - flake8-use-fstring ~=1.0
