name: qgreenland
channels:
  - conda-forge
  - defaults
dependencies:
  - python ~=3.9

  # Imported dependencies:
  - click ~=7.1
  - fiona ~=1.8
  - gdal ~=3.0
  - humanize ~=2.6
  - luigi ~=3.0
  - pyyaml ~=5.4
  - qgis ~=3.10
  - rasterio ~=1.1
  - requests ~=2.22
  - yamale ~=2.0
  - pandas ~=1.1
  - geopandas ~=0.6
  - netcdf4 ~=1.5

  # Non-imported dependencies: Task-runners, test-runners, static analysis, and
  # other utilities
  - bumpversion=0.5.3
  - flake8 ~=3.8
  - flake8-bugbear ~=20.1
  - flake8-comprehensions ~=3.2
  - flake8-docstrings ~=1.5
  - flake8-import-order ~=0.18
  - flake8-quotes ~=2.1
  - invoke ~=1.4
  - ipython
  - ipdb
  - mypy
  - pep8-naming ~=0.9
  - pytest ~=5.3
  - pytest-cov ~=2.8
  # TODO: Vulture ~=2.3
  - vulture ~=1.6
  - shellcheck ~=0.7

  # Pip dependencies could be imported or non-imported :(
  - pip:
    - flake8-debugger ~=3.2
    - flake8-use-fstring ~=1.1
    - rarfile ~=3.1
