name: qgreenland
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pyyaml=5.3
  - qgis=3.10.1
  - requests=2.22.0
  - geopandas=0.6.2
  - earthpy=0.8.0
  - luigi=2.8.11
  - rasterio=1.1.2
