name: qgreenland
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - pyyaml=5.3
  - qgis=3.10.1
  - requests=2.22.0
  - geopandas=0.6.2
  - earthpy=0.8.0
  - luigi=2.8.11
  - rasterio=1.1.2
  - invoke=1.4.0
  - flake8=3.7.9
  - flake8-import-order=0.18.1
  - flake8-quotes=2.1.1
