name: qgreenland
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8*
  - bumpversion=0.5.3
  - earthpy=0.8.0
  - flake8=3.8.3
  - flake8-bugbear=20.1.4
  - flake8-comprehensions=3.2.2
  - flake8-docstrings=1.5.0
  - flake8-import-order=0.18.1
  - flake8-quotes=2.1.1
  - geopandas=0.6.2
  - invoke=1.4.0
  - ipython
  - ipdb
  - luigi=2.8.11
  - pep8-naming=0.9.1
  - pytest=5.3.5
  - pytest-cov=2.8.1
  - pyyaml=5.3
  - qgis=3.10.7
  - rasterio=1.1.2
  - requests=2.22.0
  - vulture=1.0
  - yamale=2.0.1
  - pip:
    - flake8-debugger==3.2.1
    - flake8-use-fstring==1.0
    - rarfile==3.1
