list(include('layer'))

---
# TODO: Consider renaming file_type to "output_file_type" or something --
# currently this is used when adding layers to the project file, so we should
# consider this as output_file_type and use a new key for source file type.

layer:
  # Used for unique identification, e.g. config, filenames.
  id: str()
  # The layer name in QGIS.
  name: str()
  # descriptive text
  description: str(required=False)
  hierarchy: list()
  in_package: bool()
  # Is this layer initially "checked" as visible in QGIS?
  show: bool()
  input: include('input', required=True)

  # The name of a style (represented as .qml file in `assets/styles`). Should
  # NOT include .qml file extension
  style: str(required=False)

  steps: list(include('steps', required=True))

---
input:
  dataset: str(required=True)
  asset: str(required=True)

---
steps:
  command: list(required=False)
  template: include('template', required=False)
# TODO
#   python: include('python', required=False)
# 
---
template:
  name: str(required=True)

# ---
# python:
