map(include('layer'))

---
# TODO: Consider removing short_name key and just use the layer key
# TODO: Consider renaming file_type to "output_file_type" or something --
# currently this is used when adding layers to the project file, so we should
# consider this as output_file_type and use a new key for source file type.

# The layer's key is called its "layer_id", used for unique identification, e.g. config, filenames.
# The "name" property is for short, descriptive text, e.g. the layer name in QGIS.
layer:
  source: include('source')
  short_name: str()
  # The fully-qualified QGIS group the layer should be placed in, e.g.
  # 'Group/Subgroup/Subsubgroup'
  group_path: str()
  metadata:
    title: str()
    abstract:
      text: str()
      citation:
        text: str()
        url: str()
  # The name of a style (represented as .qml file in `assets/styles`). Should
  # NOT include .qml extension
  style: str(required=False)
  # The file extension, e.g. '.shp'
  file_type: str()
  data_type: enum('vector', 'raster')
  # Keyword arguments to rasterio `dataset.build_overviews()` method
  overviews_kwargs: include('overviews_kwargs', required=False)
  # Is this layer initially "checked" as visible in QGIS?
  visible: bool()

---
source:
  # TODO: Make the below two fields mutually-exclusive. Does Yamale support this?
  granule_ur: str(required=False)
  urls: str(required=False)

  subdir_path: str(required=False)
  base_filename: str(required=False)
  name: str(required=False)

---
overviews_kwargs:
  overview_levels: list(int())
  resampling_method: str()
