list(include('layer'))

---
layer:
  # Used for unique identification, e.g. config, filenames.
  id: str()
  # The layer name in QGIS.
  title: str()
  # descriptive text
  description: str(required=False)
  hierarchy: list()
  in_package: bool()
  # Is this layer initially "checked" as visible in QGIS?
  show: bool()
  input: include('input', required=True)

  # The name of a style (represented as .qml file in `assets/styles`). Should
  # NOT include .qml file extension
  style: str(required=False)

  steps: list(include('steps', required=True), required=False)

---
input:
  dataset: str(required=True)
  asset: str(required=True)

---
steps:
  type: enum('command', 'python', 'template')

  # TODO: Only required if type == 'template'
  template_name: str(required=False)

  # TODO: Only required if type == 'python'
  # func: str(required=False)  # e.g. qgreenland.foo.bar:baz

  # TODO: One of these is required... how to do with Yamale?
  # TODO: Are `args` only useful for `command`s?
  args: list(str(), int(), required=False)
  kwargs: map(str(), int(), map(), required=False)
