version: 2

setup: &setup
  docker:
    - image: continuumio/miniconda:4.7.12
  working_directory: ~/qgreenland

jobs:
  test:
    <<: *setup
    steps:
      - checkout
      - run:
          name: 'Run all tests (lint, config validation, etc.)'
          command: |
            apt-get update && apt-get install -y libgl1-mesa-glx
            conda env create --quiet -f environment-lock.yml
            conda init bash
            /bin/bash --login -c "conda activate qgreenland && inv test"

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^.*$/
