version: 2

setup: &setup
  docker:
    - image: continuumio/miniconda:4.7.12
  working_directory: ~/qgreenland

jobs:
  test:
    <<: *setup
    steps:
      - checkout
      - run:
          name: 'Apt install libgl1-mesa-glx'
          command: |
            # Install libgl1-mesa-glx. Import errors occur otherwise.
            # See: https://app.circleci.com/jobs/github/nsidc/qgreenland/72/parallel-runs/0/steps/0-102
            apt-get update && apt-get install -y libgl1-mesa-glx
      - run:
          name: 'Run all tests (lint, config validation, etc.)'
          command: |
            conda env create --quiet -f environment-lock.yml
            conda init bash
            /bin/bash --login -c "conda activate qgreenland && inv test"

workflows:
  version: 2

  test:
    jobs:
      - test:
          filters:
            tags:
              only: /^.*$/
