version: 2

setup: &setup
  docker:
    - image: continuumio/miniconda:4.7.12
  working_directory: ~/qgreenland

jobs:
  lint:
    <<: *setup
    steps:
      - checkout
      - run:
          name: Run flake8 linting
          command: |
            conda env create --quiet -f environment-lock.yml
            conda init bash
            /bin/bash -lc "conda activate qgreenland && inv test.lint"

workflows:
  version: 2

  test:
    jobs:
      - lint:
          filters:
            tags:
              only: /^.*$/
