# All layer groups default to collapsed and non-visible. Note that a config
# path configures only the leaf node. To configure a parent node, enumerate it
# explicitly.

Reference:
  # This is the top group, so even if we set expanded to False, it would show
  # as expanded.
  show: True
  expand: True

Reference/QGreenland boundaries:
  show: True
  expand: False

Reference/Borders:
  show: True
  expand: False

Places:
  show: False
  expand: False

Sea ice/Weekly age (12.5 km):
  show: False
  expand: True

Sea ice/Monthly mean concentration (25 km):
  show: False
  expand: True

Basemaps:
  show: True
  expand: True
