# The top level layer config -- layers are injected from their respective YAML
# files to construct a full nested hierarchy of layers and their
# configurations.

Reference:
  Borders: borders.yml

Biology:
  Fish: fish.yml

Geophysics:
  World Magnetic Model: wmm.yml

Basemaps: basemaps.yml

# Optional key; if provided, only includes the given layers
# include_layers: [ layer_id1, layer_id2 ]
# Optional key; if provided, excludes the given layers:
# exclude_layers: [ layer_id3, layer_id4 ]
