Miscellaneous:
  visible: False
  # The first group will be automatically expanded by QGIS, but we don't want
  # that:(
  expanded: False

Miscellaneous/Place names:
  visible: False
  expanded: False

Miscellaneous/Latitude lines:
  visible: False
  expanded: False

Miscellaneous/Longitude lines:
  visible: False
  expanded: False


Atmosphere:
  visible: False
  expanded: False

Atmosphere/RACMO model output:
  visible: False
  expanded: False

Atmosphere/ERA5 Re-analysis:
  visible: False
  expanded: False


Biology:
  visible: False 
  expanded: False

Biology/Fish:
  visible: False
  expanded: False

Biology/Birds:
  visible: False
  expanded: False

Biology/Mammals:
  visible: False
  expanded: False

Biology/Vegetation:
  visible: False 
  expanded: True 


Built environment:
  visible: True
  expanded: False


Environmental management:
  visible: False
  expanded: False

Environmental management/Marine protected zones:
  visible: False
  expanded: False

Environmental management/Exclusive economic zones:
  visible: False
  expanded: False


Frozen ground:
  visible: False
  expanded: False


Future projections:
  visible: False
  expanded: False


Glaciology:
  visible: False
  expanded: False

Glaciology/Glacier terminus positions 2000-2017:
  visible: False
  expanded: False

# TODO: Do we need this group? Why would we want >1 layer in this group?
Glaciology/Ice sheet velocity:
  visible: False
  expanded: False

# TODO: Do we need this group? Why would we want >1 layer in this group?
Glaciology/Ice thickness change:
  visible: False
  expanded: False


Geology & natural resources:
  visible: False
  expanded: False


Geophysics:
  visible: False
  expanded: False


Human activity:
  visible: False
  expanded: False

Human activity/Arctic shipping:
  visible: False
  expanded: False

Human activity/Research stations:
  visible: False
  expanded: False

Human activity/Historic expedition routes and stations:
  visible: False
  expanded: False


Human health:
  visible: False
  expanded: False


Hydrology:
  visible: False
  expanded: False


Oceanography:
  visible: False
  expanded: False

Oceanography/IHO-ICO GEBCO Undersea feature names:
  visible: False
  expanded: False


Sea ice:
  visible: False
  expanded: False

Sea ice/Median ice extent:
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km):
  visible: False
  expanded: True

Sea ice/NSIDC Concentration (25 km)/September (min extent):
  visible: False
  expanded: False

Sea ice/NSIDC Concentration (25 km)/Feb or March (max extent):
  visible: False
  expanded: False


Social Science:
  visible: False
  expanded: False


Terrain models:
  visible: False
  expanded: False

Terrain models/BedMachine:
  visible: False
  expanded: False


Satellite imagery:
  visible: False
  expanded: False


Basemaps:
  visible: True
  expanded: False
