- id: coastlines
  data_source: coastlines.only
  file_type: 'shp'
  data_type: 'vector'
  title: 'Natural Earth Coastlines'
  visible: True
  group_path: 'Basemaps'


- id: arctic_dem
  data_source: arctic_dem.only
  file_type: 'tif'
  data_type: 'raster'
  title: 'Arctic DEM (1km mosaic)'
  style: 'arctic_dem'
  overviews_kwargs:
    overview_levels: [2, 4, 8, 16]
    resampling_method: average
  visible: True
  group_path: 'Basemaps'


- &bedmachine
  id: bedmachine_bed
  data_source: bedmachine.only
  file_type: 'tif'
  data_type: 'raster'
  title: 'IceBridge BedMachine Greenland, Version 3 Bedrock Elevation'
  style: 'bedmachine_bed'
  warp_kwargs:
    xRes: 1000
    yRes: 1000
  visible: True
  group_path: 'Basemaps/Bedmachine'


- <<: *bedmachine
  id: bedmachine_surface
  title: 'IceBridge BedMachine Greenland, Version 3 Surface Elevation'
  style: null
  visible: False


- <<: *bedmachine
  id: bedmachine_thickness
  title: 'IceBridge BedMachine Greenland, Version 3 Ice Thickness'
  style: null
  visible: False


- &glacier_terminus
  id: glacier_terminus_glacier_ids
  data_source: glacier_terminus.glacier_ids
  title: 'MEaSUREs Annual Greenland Outlet Glacier Terminus Positions from SAR Mosaics'
  file_type: 'shp'
  data_type: 'vector'
  group_path: 'Glaciology'
  visible: True

- <<: *glacier_terminus
  id: glacier_terminus_2000_2001
  data_source: glacier_terminus.2000_2001

- <<: *glacier_terminus
  id: glacier_terminus_2005_2006
  data_source: glacier_terminus.2004_2006

- <<: *glacier_terminus
  id: glacier_terminus_2006_2007
  data_source: glacier_terminus.2006_2007

- <<: *glacier_terminus
  id: glacier_terminus_2007_2008
  data_source: glacier_terminus.2007_2008

- <<: *glacier_terminus
  id: glacier_terminus_2008_2009
  data_source: glacier_terminus.2012_2013

- <<: *glacier_terminus
  id: glacier_terminus_2012_2013
  data_source: glacier_terminus.2012_2013

- <<: *glacier_terminus
  id: glacier_terminus_2014_2015
  data_source: glacier_terminus.2014_2015

- <<: *glacier_terminus
  id: glacier_terminus_2015_2016
  data_source: glacier_terminus.2015_2016

- <<: *glacier_terminus
  id: glacier_terminus_2016_2017
  data_source: glacier_terminus.2016_2017
