coastlines:
  source:
    url: 'https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/10m/physical/ne_10m_coastline.zip'
  short_name: 'ne_coastlines'
  file_type: 'shp'
  data_type: 'vector'
  metadata:
    title: 'Natural Earth Coastlines'
    abstract:
      text:  'Natural Earth Coastlines (Public Domain)'
      citation:
        text: 'Made with Natural Earth'
        url: 'https://github.com/nvkelso/natural-earth-vector/blob/master/LICENSE.md'
  visible: True
  path: 'Basemaps'


arctic_dem:
  source:
    url: 'http://data.pgc.umn.edu/elev/dem/setsm/ArcticDEM/mosaic/v3.0/1km/arcticdem_mosaic_1km_v3.0.tif'
  short_name: 'arctic_dem'
  file_type: 'tif'
  data_type: 'raster'
  metadata:
    title: 'Arctic DEM (1km mosaic)'
    abstract:
      text: 'ArcticDEM is an NGA-NSF public-private initiative to automatically produce a high-resolution, high quality, digital surface model (DSM) of the Arctic using optical stereo imagery, high-performance computing, and open source photogrammetry software.'
      citation:
        text: 'Data provided by the Polar Geospatial Center. Porter, Claire; Morin, Paul; Howat, Ian; Noh, Myoung-Jon; Bates, Brian; Peterman, Kenneth; Keesey, Scott; Schlenk, Matthew; Gardiner, Judith; Tomko, Karen; Willis, Michael; Kelleher, Cole; Cloutier, Michael; Husby, Eric; Foga, Steven; Nakamura, Hitomi; Platson, Melisa; Wethington, Michael, Jr.; Williamson, Cathleen; Bauer, Gregory; Enos, Jeremy; Arnold, Galen; Kramer, William; Becker, Peter; Doshi, Abhijit; D’Souza, Cristelle; Cummens, Pat; Laurier, Fabien; Bojesen, Mikkel, 2018, “ArcticDEM”, https://doi.org/10.7910/DVN/OHHUKH, Harvard Dataverse, V1, 2020-01-23'
        url: 'https://www.pgc.umn.edu/data/arcticdem/'
  style: 'arctic_dem'
  overviews_kwargs:
    overview_levels: [2, 4, 8, 16]
    resampling_method: average
  visible: True
  path: 'Basemaps'


bedmachine_bed: &bedmachine
  source:
    name: 'bedmachine'
    cmr:
      short_name: 'IDBMG4'
      version: 3
  short_name: 'bedmachine_bed'
  file_type: 'tif'
  data_type: 'raster'
  metadata: &bedmachine_metadata
    title: 'IceBridge BedMachine Greenland, Version 3 Bedrock Elevation'
    abstract:
      text: 'This data set contains a bed topography/bathymetry map of Greenland based on mass conservation, multi-beam data, and other techniques. It also includes surface elevation and ice thickness data, as well as an ice/ocean/land mask.'
      citation:
        text: 'Morlighem, M. et al. 2017, updated 2018. IceBridge BedMachine Greenland, Version 3. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/2CIX82HUV88Y. 2020/02/07.'
        url: 'https://doi.org/10.5067/2CIX82HUV88Y'
  style: 'bedmachine_bed'
  warp_kwargs:
    xRes: 1000
    yRes: 1000
  visible: True
  path: 'Basemaps/Bedmachine'


bedmachine_surface:
  <<: *bedmachine
  metadata:
    <<: *bedmachine_metadata
    title: 'IceBridge BedMachine Greenland, Version 3 Surface Elevation'
  short_name: 'bedmachine_surface'
  style: null
  visible: False


bedmachine_thickness:
  <<: *bedmachine
  metadata:
    <<: *bedmachine_metadata
    title: 'IceBridge BedMachine Greenland, Version 3 Ice Thickness'
  short_name: 'bedmachine_thickness'
  style: null
  visible: False


glacier_terminus:
  source:
    - granule_ur: 'SC:NSIDC-0642.001:125860173'
      subdir_path: 2013
      base_filename: termini_2013_NSIDC
    - granule_ur: 'SC:NSIDC-0642.001:125860175'
      subdir_path: 2016
      base_filename: termini_2016_NSIDC
  metadata:
    title: 'MEaSUREs Annual Greenland Outlet Glacier Terminus Positions from SAR Mosaics'
    abstract:
      text: 'This data set, part of the NASA Making Earth System Data Records for Use in Research Environments (MEaSUREs) program, provides Greenland outlet glacier terminus positions created from MEaSUREs Synthetic Aperture Radar (SAR) mosaics and Landsat 8 OLI imagery.'
      citation:
        text: 'Joughin, I., T. Moon, J. Joughin, and T. Black. 2015, 2017. MEaSUREs Annual Greenland Outlet Glacier Terminus Positions from SAR Mosaics, Version 1. [Indicate subset used]. Boulder, Colorado USA. NASA National Snow and Ice Data Center Distributed Active Archive Center. doi: https://doi.org/10.5067/DC0MLBOCL3EL. 2020/02/12.'
        url: 'https://doi.org/10.5067/DC0MLBOCL3EL'
  short_name: 'glacier_terminus'
  file_type: 'shp'
  data_type: 'vector'
  path: 'Glaciology'
  visible: True
