# All layer groups default to collapsed and non-visible. Note that a config
# path configures only the leaf node. To configure a parent node, enumerate it
# explicitly.

Miscellaneous:
  # This is the top group, so even if we set expanded to False, it would show
  # as expanded.
  visible: True
  expanded: True

Built environment:
  visible: True
  expanded: False

Sea ice/Ice age (12.5 km):
  visible: False
  expanded: True

Sea ice/Concentration (25 km):
  visible: False
  expanded: True

Basemaps:
  visible: True
  expanded: True
