Basemaps:
  visible: True
  expanded: True

Glaciology:
  visible: True
  expanded: True

Glaciology/Glacier Terminus:
  visible: True
  expanded: False

Geophysics:
  visible: True
  expanded: True

Geophysics/IceBridge BedMachine:
  visible: True
  expanded: False

Geology & natural resources:
  visible: True
  expanded: False

# TODO paleontology better term?
Paleo-data:
  visible: True
  expanded: False

# TODO: Should "glaciology" and "sea ice" be subgroups to Cryosphere?
Cryosphere:
  visible: True
  expanded: False

Atmosphere:
  visible: True
  expanded: False

Oceanography:
  visible: True
  expanded: False

Ecology:
  visible: True
  expanded: False

Biology:
  visible: True
  expanded: False

Hydrology:
  visible: True
  expanded: False

Built environment:
  visible: True
  expanded: False

Human health:
  visible: True
  expanded: False

Political science:
  visible: True
  expanded: False

Fisheries:
  visible: True
  expanded: False

Birds:
  visible: True
  expanded: False

Mammals:
  visible: True
  expanded: False

Anthropology:
  visible: True
  expanded: False

Future predictions:
  visible: True
  expanded: False

Early explorations:
  visible: True
  expanded: False
