# All layer groups default to collapsed and non-visible. Note that a config
# path configures only the leaf node. To configure a parent node, enumerate it
# explicitly.

Built environment:
  visible: True
  expanded: False

Sea ice/Ice Age (12.5 km):
  visible: False
  expanded: True

Sea ice/Concentration (25 km):
  visible: False
  expanded: True

Basemaps:
  visible: True
  expanded: False
