#################
# Miscellaneous #
#################

- id: utm_zones
  title: Universal Transverse Mercator (UTM) Zones
  data_source: utm_zones.only
  ingest_task: utm_zones
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Miscellaneous'
  style: 'transparent_shape'


- id: arctic_circle
  title: Arctic Circle (66.567 degrees North)
  data_source: arctic_circle.only
  ingest_task: local_shapefile
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Miscellaneous'
  ogr2ogr_kwargs:
    input_filename: 'arctic_circle.geojson'
    s_srs: 'EPSG:4326'
    t_srs: 'EPSG:4326'
    segmentize: 1


###########
# Biology #
###########

- id: vegetation_biomass_2010
  title: 'Vegetation Biomass 2010 (1km)'
  description: 'Estimated above ground plant biomass for the tundra biome in kilograms per square meter. Based on trans-Arctic field data and AVHRR NDVI.'
  data_source: arctic_vegetation_biomass_2010.only
  ingest_task: arctic_vegetation
  file_type: '.tif'
  data_type: 'raster'
  visible: False
  group_path: 'Biology/Vegetation'
  style: 'arctic_vegetation_biomass'


#####################
# Built environment #
#####################

- id: populated_places
  title: 'Populated Places'
  data_source: populated_places.only
  ingest_task: zipped_shapefile
  file_type: '.shp'
  data_type: 'vector'
  # style: 'populated_places'
  subset_kwargs:
    xmin: -796814.1
    ymin: -322934.6
    xmax: 1103185.9
    ymax: -3599419.2
  # TODO: Enable a style with labels for placenames, make visible again
  visible: False
  group_path: 'Built environment'


#################
# Frozen ground #
#################

- id: permaice
  title: 'Permafrost and Ground-Ice (12.5km)'
  description: 'Soil characteristics categorized by permafrost extent, ground ice content, overburden thickness, and exposed bedrock.'
  data_source: permaice_nhipa.only
  ingest_task: permaice
  file_type: '.tif'
  data_type: 'raster'
  style: 'permaice'
  visible: False
  group_path: 'Frozen ground'
  warp_kwargs:
    xRes: 12500
    yRes: 12500
    resampleAlg: 'near'
    srcSRS: '+proj=laea +a=6371228.000 +b=6371228.000 +lon_0=0 +lat_0=90 +x_0=0 +y_0=0'


##############
# Glaciology #
##############

- &glacier_terminus
  id: glacier_terminus_glacier_ids
  title: 'Glacier IDs'
  data_source: glacier_terminus.glacier_ids
  ingest_task: glacier_terminus
  file_type: '.shp'
  data_type: 'vector'
  group_path: 'Glaciology/Glacier terminus positions 2000-2017'
  visible: False

- <<: *glacier_terminus
  id: glacier_terminus_2000_2001
  title: 'Glacier Termini 2000 to 2001'
  data_source: glacier_terminus.2000_2001
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2005_2006
  title: 'Glacier Termini 2005 to 2006'
  data_source: glacier_terminus.2005_2006
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2006_2007
  title: 'Glacier Termini 2006 to 2007'
  data_source: glacier_terminus.2006_2007
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2007_2008
  title: 'Glacier Termini 2007 to 2008'
  data_source: glacier_terminus.2007_2008
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2008_2009
  title: 'Glacier Termini 2008 to 2009'
  data_source: glacier_terminus.2008_2009
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2012_2013
  title: 'Glacier Termini 2012 to 2013'
  data_source: glacier_terminus.2012_2013
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2014_2015
  title: 'Glacier Termini 2014 to 2015'
  data_source: glacier_terminus.2014_2015
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2015_2016
  title: 'Glacier Termini 2015 to 2016'
  data_source: glacier_terminus.2015_2016
  visible: True


- <<: *glacier_terminus
  id: glacier_terminus_2016_2017
  title: 'Glacier Termini 2016 to 2017'
  data_source: glacier_terminus.2016_2017
  visible: True


- id: velocity_mosaic
  title: 'Ice Sheet Velocity (500m)'
  description: 'Magnitude of velocity in meters per year.'
  data_source: velocity_mosaic.only
  ingest_task: velocity_mosaic
  ingest_task_kwargs: {'extract_dataset': 'v'}
  file_type: '.tif'
  data_type: 'raster'
  style: 'ice_sheet_velocity'
  overviews_kwargs:
    overview_levels: [2, 4, 8, 16]
    resampling_method: average
  warp_kwargs:
    xRes: 500
    yRes: 500
  visible: True
  group_path: 'Glaciology/Ice sheet velocity'


- id: ice_thickness_change
  title: 'Ice Sheet Mass Change 2003-2019 (5km)'
  # TODO: better description.
  description: 'Mass-change in meters of ice-equivalent per year.'
  data_source: icesheet_height_and_thickness_change.only
  ingest_task: ice_thickness_change
  file_type: '.tif'
  data_type: 'raster'
  style: 'ice_thickness_change'
  decompress_kwargs:
    extract_file: 'ICESat1_ICESat2_mass_change/gris.tif'
  visible: False
  # TODO: Does this count as glaciology?
  group_path: 'Glaciology/Ice thickness change'


###############################
# Geology & natural resources #
###############################


- id: soil_types
  title: 'Soil Characteristics'
  description: 'Polygons representing dominant soil characteristics with percentage polygon area for each soil type. Data coverage limited to Greenland.'
  data_source: soil_types.only
  ingest_task: gzipped_shapefile_parts
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Geology & natural resources'
  override_source_projection: '+proj=laea +a=6370997.00 +b=6370997.00 +lat_0=90 +lon_0=180 +x_0=0 +y_0=0'
  style: 'soil_types'


#############
# Hydrology #
#############

- id: hydrologic_subbasins
  title: 'Hydrologic Sub-Basins'
  description: 'Polygons of ice sheet hydrologic sub-basins with area in square kilometers.'
  data_source: hydrologic_subbasins.only
  ingest_task: rarred_shapefile
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Hydrology'
  override_source_projection: 'ESRI:102018'


##################
# Sea ice #
##################

# sea ice median extent polylines:
- &seaice_median_extent
  id: seaice_median_extent_01
  title: 'January Median Sea Ice Extent'
  description: 'Median extent from the period 1981 through 2010.'
  data_source: seaice_index.median_extent_line_01
  ingest_task: 'zipped_shapefile'
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Sea ice/Median ice extent'

- <<: *seaice_median_extent
  id: seaice_median_extent_02
  title: 'Febuary Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_02


- <<: *seaice_median_extent
  id: seaice_median_extent_03
  title: 'March Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_03


- <<: *seaice_median_extent
  id: seaice_median_extent_04
  title: 'April Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_04


- <<: *seaice_median_extent
  id: seaice_median_extent_05
  title: 'May Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_05


- <<: *seaice_median_extent
  id: seaice_median_extent_06
  title: 'June Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_06


- <<: *seaice_median_extent
  id: seaice_median_extent_07
  title: 'July Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_07


- <<: *seaice_median_extent
  id: seaice_median_extent_08
  title: 'August Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_08


- <<: *seaice_median_extent
  id: seaice_median_extent_09
  title: 'September Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_09


- <<: *seaice_median_extent
  id: seaice_median_extent_10
  title: 'October Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_10


- <<: *seaice_median_extent
  id: seaice_median_extent_11
  title: 'November Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_11


- <<: *seaice_median_extent
  id: seaice_median_extent_12
  title: 'December Median Sea Ice Extent'
  data_source: seaice_index.median_extent_line_12


- &seaice_minimum_concentration
  id: minimum_concentration_2009
  title: 'NSIDC Sea Ice Concentration September 2009'
  description: 'Concentration of sea ice as a 10x scaled percentage (e.g., 999 = 99.9%). Values under 150 (15%) are considered to be open water.'
  data_source: seaice_index.minimum_concentration_2009
  style: 'sea_ice_concentration'
  ingest_task: 'raster'
  file_type: '.tif'
  data_type: 'raster'
  visible: False
  group_path: 'Sea ice/NSIDC Concentration (25 km)/September (min extent)'


# sea ice min extent monthly concentration:
- <<: *seaice_minimum_concentration
  id: minimum_concentration_2010
  title: 'NSIDC Sea Ice Concentration September 2010'
  data_source: seaice_index.minimum_concentration_2010


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2011
  title: 'NSIDC Sea Ice Concentration September 2011'
  data_source: seaice_index.minimum_concentration_2011


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2012
  title: 'NSIDC Sea Ice Concentration September 2012'
  data_source: seaice_index.minimum_concentration_2012


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2013
  title: 'NSIDC Sea Ice Concentration September 2013'
  data_source: seaice_index.minimum_concentration_2013


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2014
  title: 'NSIDC Sea Ice Concentration September 2014'
  data_source: seaice_index.minimum_concentration_2014


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2015
  title: 'NSIDC Sea Ice Concentration September 2015'
  data_source: seaice_index.minimum_concentration_2015


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2016
  title: 'NSIDC Sea Ice Concentration September 2016'
  data_source: seaice_index.minimum_concentration_2016


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2017
  title: 'NSIDC Sea Ice Concentration September 2017'
  data_source: seaice_index.minimum_concentration_2017


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2018
  title: 'NSIDC Sea Ice Concentration September 2018'
  data_source: seaice_index.minimum_concentration_2018


- <<: *seaice_minimum_concentration
  id: minimum_concentration_2019
  title: 'NSIDC Sea Ice Concentration September 2019'
  data_source: seaice_index.minimum_concentration_2019

# sea ice max extent monthly concentrations:
- &seaice_maximum_concentration
  id: maximum_concentration_2009
  title: 'NSIDC Sea Ice Concentration March 2009'
  description: 'Concentration of sea ice as a 10x scaled percentage (e.g., 999 = 99.9%). Values under 150 (15%) are considered to be open water.'
  data_source: seaice_index.maximum_concentration_2009
  style: 'sea_ice_concentration'
  ingest_task: 'raster'
  file_type: '.tif'
  data_type: 'raster'
  visible: False
  group_path: 'Sea ice/NSIDC Concentration (25 km)/Feb|March (max extent)'


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2010
  title: 'NSIDC Sea Ice Concentration March 2010'
  data_source: seaice_index.maximum_concentration_2010


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2011
  title: 'NSIDC Sea Ice Concentration March 2011'
  data_source: seaice_index.maximum_concentration_2011


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2012
  title: 'NSIDC Sea Ice Concentration March 2012'
  data_source: seaice_index.maximum_concentration_2012


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2013
  title: 'NSIDC Sea Ice Concentration March 2013'
  data_source: seaice_index.maximum_concentration_2013


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2014
  title: 'NSIDC Sea Ice Concentration March 2014'
  data_source: seaice_index.maximum_concentration_2014


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2015
  title: 'NSIDC Sea Ice Concentration February 2015'
  data_source: seaice_index.maximum_concentration_2015


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2016
  title: 'NSIDC Sea Ice Concentration March 2016'
  data_source: seaice_index.maximum_concentration_2016


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2017
  title: 'NSIDC Sea Ice Concentration March 2017'
  data_source: seaice_index.maximum_concentration_2017


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2018
  title: 'NSIDC Sea Ice Concentration March 2018'
  data_source: seaice_index.maximum_concentration_2018


- <<: *seaice_maximum_concentration
  id: maximum_concentration_2019
  title: 'NSIDC Sea Ice Concentration March 2019'
  data_source: seaice_index.maximum_concentration_2019


##################
# Terrain models #
##################

- &bedmachine
  id: bedmachine_bed
  title: 'Bedrock Elevation (1km)'
  description: 'Bedrock elevation in meters. Source is mass conservation (Mathieu Morlighem).'
  data_source: bedmachine.only
  ingest_task: bedmachine
  ingest_task_kwargs: {'extract_dataset': 'bed'}
  file_type: '.tif'
  data_type: 'raster'
  style: 'bedmachine_bed'
  warp_kwargs:
    xRes: 1000
    yRes: 1000
  visible: True
  group_path: 'Terrain models/BedMachine'


- <<: *bedmachine
  id: bedmachine_surface
  title: 'Surface Elevation (1km)'
  description: 'Surface elevation in meters. Source is gimpdem v2.1 (http://bprc.osu.edu/GDG/gimpdem.php)'
  ingest_task_kwargs: {'extract_dataset': 'surface'}
  style: null
  visible: False


- <<: *bedmachine
  id: bedmachine_thickness
  title: 'Ice Thickness (1km)'
  description: 'Ice thickness in meters. Source is Mass conservation (Mathieu Morlighem)'
  ingest_task_kwargs: {'extract_dataset': 'thickness'}
  style: null
  visible: False


- <<: *bedmachine
  id: bedmachine_errbed
  title: 'Bedrock Elevation/Ice Thickness Error (1km)'
  ingest_task_kwargs: {'extract_dataset': 'errbed'}
  style: null
  visible: False


- id: arctic_dem
  title: 'Arctic DEM (1km)'
  description: 'Surface elevation in meters.'
  data_source: arctic_dem.only
  ingest_task: 'raster'
  file_type: '.tif'
  data_type: 'raster'
  style: 'arctic_dem'
  overviews_kwargs:
    overview_levels: [2, 4, 8, 16]
    resampling_method: average
  visible: False
  group_path: 'Terrain models'


############
# BASEMAPS #
############


- id: coastlines
  title: 'Coastlines'
  data_source: coastlines.only
  ingest_task: zipped_shapefile
  file_type: '.shp'
  data_type: 'vector'
  visible: False
  group_path: 'Basemaps'


# NOTE: We attempted to add the corresponding NE Ocean layer, but it included
# holes for small islands which are not present on the land layer, and that was
# gross so we removed the ocean layer.
- id: land
  title: 'Land'
  data_source: land_shape.only
  ingest_task: zipped_shapefile
  file_type: '.shp'
  data_type: 'vector'
  style: 'land'
  visible: False 
  group_path: 'Basemaps'


- id: background
  title: 'Background (1km)'
  data_source: background.only
  ingest_task: background_image
  file_type: '.tif'
  data_type: 'raster'
  # NOTE: Without passing warp_kwargs, we get a black image.
  # TODO: Which of these args are necessary to avoid that?
  warp_kwargs:
    xRes: 1000
    yRes: 1000
    # Attempt to avoid pole hole and nodata line where east and west edges of
    # the original image meet after polar wrapping. TODO: This doesn't actually
    # get rid of the line.
    warpOptions: ['SOURCE_EXTRA=100', 'SAMPLE_GRID=YES']
  visible: True
  group_path: 'Basemaps'
