# What about combining id, name, group_path in to one triple-duty unique
# identifier? One problem with this is coupling the group path with the unique
# identifier -- you have to change the identifier to change the groups a layer is
# shown in on the QGIS layers panel. e.g.:
#     - layer: 'Basemaps/Background (500m)'

- id: 'background'  # The on-disk folder containing the data
  title: 'Background (500m)'  # The layer name in the QGIS panel
  description: >-
    Stylized shaded-relief map for providing a general sense of geography.
  hierarchy: ['Basemaps']  # The group(s, if nested) in the QGIS panel that this layer is in
  in_package: True
  show: True  # Whether this layer is "shown" in QGIS
  # TODO: Make "input" into a "step"? i.e.:
  # - fetch:
  #     dataset: 'background'
  #     asset: 'high_res'
  input:
    dataset: 'background'
    asset: 'high_res'
  steps:
    # Extract the data
    - type: 'command'
      args: ['unzip', '{input_dir}/*.zip', '-d', '{output_dir}']

    # - template:
    #     name: 'warp_multiple_steps'
    #     output_fn: 'foo.tif'
    #     kwargs:
    #       foo: bar
    # - template:
    #     name: 'build_overviews'
    #     output_fn: 'foo.tif'
    #     kwargs:
    #       baz: qux
    # - template:
    #     name: 'compress'
    #     output_fn: 'foo.tif'
    #     kwargs:
    #       banana: manaña 
    - type: 'template'
      template_name: 'warp_and_cut'
      kwargs:
        # TODO: All templates have input and output files. Promote to top-level
        # step key?
        input_file: '{input_dir}/NE2_HR_LC_SR_W/NE2_HR_LC_SR_W.tif'
        output_file: '{output_dir}/warped_and_cut.tif'

        xRes: 500
        yRes: 500
        # TODO: Abstract boundaries... as slugs? e.g.:
        #     {boundaries.background.extent['minx']}
        #     {boundaries.background.extent['miny']}
        #     {boundaries.background.extent['maxx']}
        #     {boundaries.background.extent['maxy']}
        target_extent: '-5774572.727595 -5774572.727595 5774572.727595 5774572.727595'
        cut_file: '{assets_dir}/latitude_shape_40_degrees.geojson'

    # Add overviews
    - type: 'template'
      template_name: 'build_overviews'
      kwargs:
        input_file: '{input_dir}/warped_and_cut.tif'
        output_file: '{output_dir}/overviews.tif'
