# What about combining id, name, group_path in to one triple-duty unique
# identifier? One problem with this is coupling the group path with the unique
# identifier -- you have to change the identifier to change the groups a layer is
# shown in on the QGIS layers panel. e.g.:
#     - layer: 'Basemaps/Background (500m)'

- id: background  # The on-disk folder containing the data
  title: 'Background (500m)'  # The layer name in the QGIS panel
  # TODO: originally called 'group_path', but that's a confusing name. Do we like 'hierarchy'?
  hierarchy: ['Basemaps']  # The group(s, if nested) in the QGIS panel that this layer is in
  in_package: True
  show: True  # Whether this layer is "shown" in QGIS
  # TODO: Make "input" into a "step"? i.e.:
  # - fetch:
  #     dataset: 'background'
  #     asset: 'high_res'
  input:
    dataset: 'background'
    asset: 'high_res'
  steps:
    - command: ['unzip', '{input_dir}/*.zip', '-d', '{output_dir}']
    # "cut hack". Instead of doing one warp operation, we break it into two
    # pieces to avoid:
    #
    #     Self-intersection at or near point 21540.002777633181
    #     2999.9999813578638\nERROR 1: Cutline polygon is invalid.\n
    #
    # TODO: Template!
    # - command:
    #   - 'gdalwarp'

    #   - '{input_dir}/NE2_HR_LC_SR_W/NE2_HR_LC_SR_W.tif'
    #   - '{output_dir}/hacked.tif'
    - command:
      - 'gdalwarp'
      - '-t_srs'  # dstCRS
      - 'EPSG:3413'
      - '-cutline'  # CutlineDSName
      # TODO: Abstract the boundary filenames?
      - '{assets_dir}/local_data/latitude_shape_40_degrees.geojson'
      - '-crop_to_cutline'  # CropToCutline=True
      - '-co'  # creationOptions=['COMPRESS=DEFLATE']
      - 'COMPRESS=DEFLATE'
      - '-tr'  # xRes=500, yRes=500
      - '500'
      - '500'
      - '-dstnodata'  # dstNodata
      - '0'
      - '-wo'  # warpOptions=['SOURCE_EXTRA=100', 'SAMPLE_GRID=YES']
      - 'SOURCE_EXTRA=100'
      - '-wo'
      - 'SAMPLE_GRID=YES'
      - '{input_dir}/hacked.tif'
      - '{output_dir}/warped.tif'

    - command: ['gdalwhatever', '-i', '{input_dir}/foo.tif', '-o', '{output_dir}/foo.shp']
    - template:
        name: warp_multiple_steps
        output_fn: 'foo.tif'
    - template:
        name: build_overviews
        output_fn: 'foo.tif'
    - template:
        name: compress
        output_fn: 'foo.tif'




# # OLD:
# - id: background
#   title: 'Background (500m)'
#   visible: True
#   group_path: 'Basemaps'
#   boundary: 'background'
#   data_source: background.high_res
#   ingest_task: background_image
#   file_type: '.tif'
#   data_type: 'raster'
#   overviews_kwargs:
#     overview_levels: [2, 4, 8, 16]
#     resampling_method: average
#   # NOTE: Without passing warp_kwargs, we get a black image.
#   # TODO: Which of these args are necessary to avoid that?
#   warp_kwargs:
#     # We measured the size of the pixels in the input datasource (WGS84) at the
#     # North and South ends of Greenland and found a range of roughly 250m to
#     # 900m. 500m is somewhere in the middle, so some of greenland will be
#     # downsampled, and some will be oversampled.
#     xRes: 500
#     yRes: 500
#     dstNodata: 0
#     # Attempt to avoid pole hole and nodata line where east and west edges of
#     # the original image meet after polar wrapping. TODO: This doesn't actually
#     # get rid of the line.
#     warpOptions: ['SOURCE_EXTRA=100', 'SAMPLE_GRID=YES']
