# OLD:
- id: bas_greenland_coastlines
  title: 'Greenland coastlines 2017'
  description: >-
    This layer should be used as the 'reference coastline' for Greenland.
  visible: True
  group_path: 'Reference/Borders'
  style: greenland_coastline
  boundary: 'background'
  data_source: bas_coastlines.only
  ingest_task: zipped_vector
  file_type: '.gpkg'
  data_type: 'vector'
