- id: 'image_mosaic_2019'
  title: 'Greenland image mosaic 2019 (10m)'
  description: 'Sentinel-2 multispectral satellite imagery from 2019.'
  show: False
  in_package: True
  hierarchy: ['Internet-required data']
  style: 'transparent_rgb'
  input:
    dataset: 'image_mosaic'
    asset: '2019'


# TODO: why does QGIS only show data back to 2011. We clearly have data from
# before that.
- id: 'g02135_polyline_n'
  title: 'Sea Ice Index'
  description: >-
      Lines representing monthly sea ice extent edges. Note that aside from 2016
      to present, most of the data is missing.
  show: False
  in_package: True
  hierarchy: ['Internet-required data', 'Sea Ice']
  input:
    dataset: 'sea_ice_index'
    asset: 'monthly_polyline_n'
