- &wmm_north_poles
  id: wmm_north_poles
  title: 'Geomagnetic North dip pole 2020-2025'
  description: >-
    The locations of northern hemisphere dip poles (2020-2025) from the World
    Magnetic Model (WMM) 2020 model.

    The geomagnetic dip poles are positions on the Earth's surface where the
    geomagnetic field is perpendicular to the ellipsoid, that is, vertical. The
    north and south dip poles do not have to be (and are not now) antipodal.

    These model dip poles are computed from all the Gauss coefficients using an
    iterative method. In 2020.0 the north dip pole computed from WMM2020 is
    located at longitude 164.04°E and geodetic latitude 86.50°N and the south
    dip pole at longitude 135.88°E and geodetic latitude 64.07°S.
  hierarchy: ['Geophysics', 'World Magnetic Model', 'Dip poles']
  in_package: True
  show: False
  input:
    dataset: 'world_magnetic_model'
    asset: 'geomagnetic_north_pole'
  style: 'geomagnetic_north_pole'
  steps:
    - command: ['fooo', 'TODO']

- &boz_2020
  id: wmm_boz_2020
  title: 'Blackout zones'
  description: >-
    Based on the WMM military specification, we define “Blackout Zones” (BoZ)
    around the north and south magnetic poles where compass accuracy is highly
    degraded. The BoZ are defined as regions around the north and south magnetic
    poles where the horizontal intensity of Earth’s magnetic field (H) is less
    than 2000 nT. In BoZs, WMM declination values are not accurate and compasses
    are unreliable.

    We additionally define a “Caution Zone” (2000 nT <= H < 6000 nT) around the
    BoZ, where caution must be exercised while using a compass. Compass accuracy
    may be degraded in this region.
  show: False
  hierarchy: ['Geophysics', 'World Magnetic Model', '2020']
  in_package: True
  style: 'blackout_zones'
  input:
    dataset: 'world_magnetic_model'
    asset: 'blackout_zones'
  steps:
    - command: ['foo', 'bar']

- &wmm_d_2020
  id: wmm_d_2020
  title: 'Main field declination (D)'
  description: &wmm_d_description >-
    Contours representing magnetic declination (D) in degrees. D is the angle
    between magnetic north and true north. D is considered positive when the
    angle measured is east of true north and negative when west.
  show: False
  hierarchy: ['Geophysics', 'World Magnetic Model', '2020']
  in_package: True
  style: 'wmm_contours'
  input:
    dataset: 'world_magnetic_model'
    asset: '2020'
  steps:
    - command: ['foo', 'bar']

# TODO: Keep only one variable from each year
# OLD:
# - &wmm_north_poles
#   id: wmm_north_poles
#   title: 'Geomagnetic North dip pole 2020-2025'
#   description: >-
#     The locations of northern hemisphere dip poles (2020-2025) from the World
#     Magnetic Model (WMM) 2020 model.
# 
#     The geomagnetic dip poles are positions on the Earth's surface where the
#     geomagnetic field is perpendicular to the ellipsoid, that is, vertical. The
#     north and south dip poles do not have to be (and are not now) antipodal.
# 
#     These model dip poles are computed from all the Gauss coefficients using an
#     iterative method. In 2020.0 the north dip pole computed from WMM2020 is
#     located at longitude 164.04°E and geodetic latitude 86.50°N and the south
#     dip pole at longitude 135.88°E and geodetic latitude 64.07°S.
#   visible: False
#   group_path: 'Geophysics/World Magnetic Model/Dip poles'
#   style: geomagnetic_north_pole
#   data_source: world_magnetic_model.geomagnetic_north_pole
#   ingest_task: delimited_text_points_vector
#   file_type: '.gpkg'
#   data_type: 'vector'
#   boundary: 'background'
#   delimited_text_vector_kwargs:
#     input_filename: 'WMM2020_NP.xy'
#     header: null
#     delimiter: ' '
#     field_names:
#       - latitude
#       - longitude
#       - year
#   ogr2ogr_kwargs:
#     s_srs: 'EPSG:4326'
#     input_filename: 'WMM2020_NP.gpkg'
# 
# - &boz_2020
#   id: wmm_boz_2020
#   title: 'Blackout zones'
#   description: >-
#     Based on the WMM military specification, we define “Blackout Zones” (BoZ)
#     around the north and south magnetic poles where compass accuracy is highly
#     degraded. The BoZ are defined as regions around the north and south magnetic
#     poles where the horizontal intensity of Earth’s magnetic field (H) is less
#     than 2000 nT. In BoZs, WMM declination values are not accurate and compasses
#     are unreliable.
# 
#     We additionally define a “Caution Zone” (2000 nT <= H < 6000 nT) around the
#     BoZ, where caution must be exercised while using a compass. Compass accuracy
#     may be degraded in this region.
#   visible: False
#   group_path: 'Geophysics/World Magnetic Model/2020'
#   style: blackout_zones
#   data_source: world_magnetic_model.blackout_zones
#   ingest_task: zipped_vector
#   file_type: '.gpkg'
#   data_type: 'vector'
#   boundary: 'background'
#   decompress_kwargs:
#     extract_files:
#       - 'BOZ_arctic_all/BOZ_2020.CPG'
#       - 'BOZ_arctic_all/BOZ_2020.dbf'
#       - 'BOZ_arctic_all/BOZ_2020.prj'
#       - 'BOZ_arctic_all/BOZ_2020.sbn'
#       - 'BOZ_arctic_all/BOZ_2020.sbx'
#       - 'BOZ_arctic_all/BOZ_2020.shp'
#       - 'BOZ_arctic_all/BOZ_2020.shp.xml'
#       - 'BOZ_arctic_all/BOZ_2020.shx'
# 
# - &wmm_d_2020
#   id: wmm_d_2020
#   title: 'Main field declination (D)'
#   description: &wmm_d_description >-
#     Contours representing magnetic declination (D) in degrees. D is the angle
#     between magnetic north and true north. D is considered positive when the
#     angle measured is east of true north and negative when west.
#   visible: False
#   group_path: 'Geophysics/World Magnetic Model/2020'
#   style: wmm_contours
#   data_source: world_magnetic_model.2020
#   ingest_task: zipped_vector
#   file_type: '.gpkg'
#   data_type: 'vector'
#   boundary: 'background'
#   decompress_kwargs:
#     extract_files:
#       - 'WMM_2020_all_shape_geographic/D_2020.cpg'
#       - 'WMM_2020_all_shape_geographic/D_2020.dbf'
#       - 'WMM_2020_all_shape_geographic/D_2020.prj'
#       - 'WMM_2020_all_shape_geographic/D_2020.sbn'
#       - 'WMM_2020_all_shape_geographic/D_2020.sbx'
#       - 'WMM_2020_all_shape_geographic/D_2020.shp'
#       - 'WMM_2020_all_shape_geographic/D_2020.shp.xml'
#       - 'WMM_2020_all_shape_geographic/D_2020.shx'
#   ogr2ogr_kwargs:
#     OGR_ENABLE_PARTIAL_REPROJECTION: True
#     dialect: sqlite
#     sql: >-
#       "SELECT
#         Geometry,
#         Contour,
#         SIGN,
#         \"INDEX\",
#         CAST(Contour AS TEXT) ||  ' °' as label
#       FROM D_2020"
