version: '3'

services:

  luigi:
    image: nsidc/luigi:dev
    build: .
    container_name: luigi
    volumes:
      - ./conf:/etc/luigi:ro
      - ./state:/luigi/state:rw
      - ./data:/luigi/data:rw
      - ../qgreenland:/luigi/tasks/qgreenland:ro
    environment:
      - EARTHDATA_USERNAME
      - EARTHDATA_PASSWORD
    ports:
      - 80:8082
