version: '3'

services:

  luigi:
    image: nsidc/luigi:dev
    build: .
    container_name: luigi
    volumes:
      - ./conf:/etc/luigi:ro
      - ./state:/luigi/state:rw
      - /share/appdata/qgreenland/QGreenland:/luigi/data:rw
      - ../qgreenland:/luigi/tasks/qgreenland:ro
    ports:
      - 8082:8082
    restart: on-failure

  webserver:
    image: nginx
    volumes:
      - /share/appdata/qgreenland/QGreenland/release/:/usr/share/nginx/html/:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 80:80
    restart: on-failure
